version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_app
      MYSQL_USER: user
      MYSQL_PASSWORD: senha12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede_local

  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: senha12345
      DB_NAME: meu_app
    depends_on:
      - db
    networks:
      - rede_local

volumes:
  db_data:

networks:
  rede_local: